.output /dev/null
SELECT dolt_config('user.name', 'Ada');
SELECT dolt_config('user.email', 'ada@example.com');
CREATE TABLE t (id INTEGER PRIMARY KEY, v TEXT);
INSERT INTO t VALUES (0, 'seed');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'seed');
INSERT INTO t VALUES (1, 'value-1');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-1');
INSERT INTO t VALUES (2, 'value-2');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-2');
INSERT INTO t VALUES (3, 'value-3');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-3');
INSERT INTO t VALUES (4, 'value-4');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-4');
INSERT INTO t VALUES (5, 'value-5');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-5');
INSERT INTO t VALUES (6, 'value-6');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-6');
INSERT INTO t VALUES (7, 'value-7');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-7');
INSERT INTO t VALUES (8, 'value-8');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-8');
INSERT INTO t VALUES (9, 'value-9');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-9');
INSERT INTO t VALUES (10, 'value-10');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-10');
INSERT INTO t VALUES (11, 'value-11');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-11');
INSERT INTO t VALUES (12, 'value-12');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-12');
INSERT INTO t VALUES (13, 'value-13');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-13');
INSERT INTO t VALUES (14, 'value-14');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-14');
INSERT INTO t VALUES (15, 'value-15');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-15');
INSERT INTO t VALUES (16, 'value-16');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-16');
INSERT INTO t VALUES (17, 'value-17');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-17');
INSERT INTO t VALUES (18, 'value-18');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-18');
INSERT INTO t VALUES (19, 'value-19');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-19');
INSERT INTO t VALUES (20, 'value-20');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-20');
INSERT INTO t VALUES (21, 'value-21');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-21');
INSERT INTO t VALUES (22, 'value-22');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-22');
INSERT INTO t VALUES (23, 'value-23');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-23');
INSERT INTO t VALUES (24, 'value-24');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-24');
INSERT INTO t VALUES (25, 'value-25');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-25');
INSERT INTO t VALUES (26, 'value-26');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-26');
INSERT INTO t VALUES (27, 'value-27');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-27');
INSERT INTO t VALUES (28, 'value-28');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-28');
INSERT INTO t VALUES (29, 'value-29');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-29');
INSERT INTO t VALUES (30, 'value-30');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-30');
INSERT INTO t VALUES (31, 'value-31');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-31');
INSERT INTO t VALUES (32, 'value-32');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-32');
INSERT INTO t VALUES (33, 'value-33');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-33');
INSERT INTO t VALUES (34, 'value-34');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-34');
INSERT INTO t VALUES (35, 'value-35');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-35');
INSERT INTO t VALUES (36, 'value-36');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-36');
INSERT INTO t VALUES (37, 'value-37');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-37');
INSERT INTO t VALUES (38, 'value-38');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-38');
INSERT INTO t VALUES (39, 'value-39');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-39');
INSERT INTO t VALUES (40, 'value-40');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-40');
INSERT INTO t VALUES (41, 'value-41');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-41');
INSERT INTO t VALUES (42, 'value-42');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-42');
INSERT INTO t VALUES (43, 'value-43');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-43');
INSERT INTO t VALUES (44, 'value-44');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-44');
INSERT INTO t VALUES (45, 'value-45');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-45');
INSERT INTO t VALUES (46, 'value-46');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-46');
INSERT INTO t VALUES (47, 'value-47');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-47');
INSERT INTO t VALUES (48, 'value-48');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-48');
INSERT INTO t VALUES (49, 'value-49');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-49');
INSERT INTO t VALUES (50, 'value-50');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-50');
INSERT INTO t VALUES (51, 'value-51');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-51');
INSERT INTO t VALUES (52, 'value-52');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-52');
INSERT INTO t VALUES (53, 'value-53');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-53');
INSERT INTO t VALUES (54, 'value-54');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-54');
INSERT INTO t VALUES (55, 'value-55');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-55');
INSERT INTO t VALUES (56, 'value-56');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-56');
INSERT INTO t VALUES (57, 'value-57');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-57');
INSERT INTO t VALUES (58, 'value-58');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-58');
INSERT INTO t VALUES (59, 'value-59');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-59');
INSERT INTO t VALUES (60, 'value-60');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-60');
INSERT INTO t VALUES (61, 'value-61');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-61');
INSERT INTO t VALUES (62, 'value-62');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-62');
INSERT INTO t VALUES (63, 'value-63');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-63');
INSERT INTO t VALUES (64, 'value-64');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-64');
INSERT INTO t VALUES (65, 'value-65');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-65');
INSERT INTO t VALUES (66, 'value-66');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-66');
INSERT INTO t VALUES (67, 'value-67');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-67');
INSERT INTO t VALUES (68, 'value-68');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-68');
INSERT INTO t VALUES (69, 'value-69');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-69');
INSERT INTO t VALUES (70, 'value-70');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-70');
INSERT INTO t VALUES (71, 'value-71');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-71');
INSERT INTO t VALUES (72, 'value-72');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-72');
INSERT INTO t VALUES (73, 'value-73');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-73');
INSERT INTO t VALUES (74, 'value-74');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-74');
INSERT INTO t VALUES (75, 'value-75');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-75');
INSERT INTO t VALUES (76, 'value-76');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-76');
INSERT INTO t VALUES (77, 'value-77');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-77');
INSERT INTO t VALUES (78, 'value-78');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-78');
INSERT INTO t VALUES (79, 'value-79');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-79');
INSERT INTO t VALUES (80, 'value-80');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-80');
INSERT INTO t VALUES (81, 'value-81');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-81');
INSERT INTO t VALUES (82, 'value-82');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-82');
INSERT INTO t VALUES (83, 'value-83');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-83');
INSERT INTO t VALUES (84, 'value-84');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-84');
INSERT INTO t VALUES (85, 'value-85');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-85');
INSERT INTO t VALUES (86, 'value-86');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-86');
INSERT INTO t VALUES (87, 'value-87');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-87');
INSERT INTO t VALUES (88, 'value-88');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-88');
INSERT INTO t VALUES (89, 'value-89');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-89');
INSERT INTO t VALUES (90, 'value-90');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-90');
INSERT INTO t VALUES (91, 'value-91');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-91');
INSERT INTO t VALUES (92, 'value-92');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-92');
INSERT INTO t VALUES (93, 'value-93');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-93');
INSERT INTO t VALUES (94, 'value-94');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-94');
INSERT INTO t VALUES (95, 'value-95');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-95');
INSERT INTO t VALUES (96, 'value-96');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-96');
INSERT INTO t VALUES (97, 'value-97');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-97');
INSERT INTO t VALUES (98, 'value-98');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-98');
INSERT INTO t VALUES (99, 'value-99');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-99');
INSERT INTO t VALUES (100, 'value-100');
SELECT dolt_add('-A');
SELECT dolt_commit('-m', 'commit-100');
.output /dev/null
SELECT count(*) FROM dolt_log;
.output stdout
SELECT count(*) FROM t;
